### ISSUE TITLE
Second player disconnects when game launches..

### ISSUE THREAD

**Issue by Brandt-J** [GD-Sync/GD-Sync-Demo-Project#2]
Hi,
I was trying to get the demo running.  Testing with Godot 4.2.1, just cloned this commit (https://github.com/GD-Sync/GD-Sync-Demo-Project/commit/a5aa7471a844219fe5ac6b95db55a8bed9077be8) and only entered my API keys.

I am connecting two players (making Godot to launch two instances of the project) and am creating a lobby with Player1, where Player2 then connects.
![image](https://github.com/GD-Sync/GD-Sync-Demo-Project/assets/34997035/12198337-57ec-49c9-8593-4827757cf78d)

When I then launch the game, I can see both players in the window of Player1, but only for a short time:
![image](https://github.com/GD-Sync/GD-Sync-Demo-Project/assets/34997035/98e6f204-eb2c-4d53-a037-54add9d2e2d5)
Player2 then disconnects and returns back to the main menu screen of the demo (with the "connect" and "quit" buttons)

There are a few error messages in the debugger:
Player 1:
![image](https://github.com/GD-Sync/GD-Sync-Demo-Project/assets/34997035/dd119c38-e3f4-49a5-8fac-b7c45695c874)

Player2:
![image](https://github.com/GD-Sync/GD-Sync-Demo-Project/assets/34997035/58da7183-94ba-44ac-b7bf-f45fc9a185e9)

Any ideas/hints?

**Comment by ThomasUijlen** [comment]
Hi there!

I have a suspicion on what might be causing this. It is an issue we discovered relatively recently. Just to confirm: Are the players staying connected when in the lobby? Do they only disconnect during scene transition when pressing start?

**Comment by Brandt-J** [comment]
Hey,
yes, I just stayed in the lobby for a few minutes with both players, but this seems to work as expected. The disconnect only happens when I launch the actual game.

**Comment by ThomasUijlen** [comment]
I suspect it is a timeout issue. The second client is probably loading for longer than 5 seconds, which causes the connection to timeout.

During scene transition/loading the game completely freezes, preventing the plugin from polling the connection. We are still figuring out a good solution for this issue. Either the plugin has to be reworked so that it somehow keeps polling while the game is frozen or the demo project has to be reworked to reestablish the connection in case it drops.

**Comment by ThomasUijlen** [comment]
GD-Sync has been updated to include multi-threaded scene switching. This loads and instantiates the new scene in a separate thread on all clients.

This should resolve the timeout issue completely as the game should no longer freeze when loading the next scene. It also now waits for all clients to complete loading the new scene before switching.
